"""add video type and subject description

Revision ID: add_video_type_subject
Revises: add_video_file_info
Create Date: 2026-05-27 09:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_video_type_subject'
down_revision = 'add_video_file_info'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_type', sa.String(length=20), nullable=True, comment='视频类型：single(单人), multiple(多人)'))
        batch_op.add_column(sa.Column('subject_description', sa.Text(), nullable=True, comment='人物主体描述（大模型生成）'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('subject_description')
        batch_op.drop_column('video_type')

    # ### end Alembic commands ###
