"""add frame_image_path to videos table

Revision ID: add_frame_image_path
Revises: add_video_type_subject
Create Date: 2026-05-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_frame_image_path'
down_revision = 'add_video_type_subject'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frame_image_path', sa.String(length=500), nullable=True, comment='框选帧图片路径（多人视频使用）'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('frame_image_path')

    # ### end Alembic commands ###
