"""add video file info

Revision ID: add_video_file_info
Revises: a1b2c3d4e5f6
Create Date: 2024-01-01

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_video_file_info'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_format', sa.String(length=20), nullable=True, comment='文件格式（扩展名）'))
        batch_op.add_column(sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小（字节）'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_format')

    # ### end Alembic commands ###
