"""Initial migration

Revision ID: d90d2b562ea3
Revises: 
Create Date: 2026-05-25 03:27:03.918615

"""
from alembic import op
import sqlalchemy as sa
import hashlib


# revision identifiers, used by Alembic.
revision = 'd90d2b562ea3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='用户 ID'),
    sa.Column('username', sa.String(length=80), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=120), nullable=False, comment='邮箱地址'),
    sa.Column('password_hash', sa.String(length=256), nullable=False, comment='密码哈希值'),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='用户头像 URL'),
    sa.Column('is_admin', sa.Boolean(), nullable=True, default=False, comment='是否为管理员'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间 (CST/UTC+8)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dancers',
    sa.Column('id', sa.Integer(), nullable=False, comment='舞者 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='舞者名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='舞者描述'),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='舞者头像 URL'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间 (CST/UTC+8)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间 (CST/UTC+8)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False, comment='视频 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户 ID'),
    sa.Column('dancer_id', sa.Integer(), nullable=False, comment='舞者 ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='视频标题'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='文件存储路径'),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True, comment='缩略图 URL'),
    sa.Column('duration', sa.Float(), nullable=True, comment='视频时长（秒）'),
    sa.Column('upload_date', sa.DateTime(), nullable=False, comment='上传时间 (CST/UTC+8)'),
    sa.Column('dance_style', sa.String(length=50), nullable=True, comment='舞蹈风格：breaking, popping, locking 等'),
    sa.ForeignKeyConstraint(['dancer_id'], ['dancers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_records',
    sa.Column('id', sa.Integer(), nullable=False, comment='进步记录 ID'),
    sa.Column('dancer_id', sa.Integer(), nullable=False, comment='舞者 ID'),
    sa.Column('skill_category', sa.String(length=100), nullable=False, comment='技能类别：rhythm, technique, creativity 等'),
    sa.Column('score', sa.Float(), nullable=False, comment='得分'),
    sa.Column('improvement_rate', sa.Float(), nullable=True, comment='进步率'),
    sa.Column('feedback', sa.Text(), nullable=True, comment='AI 生成的反馈建议'),
    sa.Column('recorded_at', sa.DateTime(), nullable=False, comment='记录时间 (CST/UTC+8)'),
    sa.Column('comparison_video_ids', sa.JSON(), nullable=True, comment='用于对比的视频 ID 列表'),
    sa.ForeignKeyConstraint(['dancer_id'], ['dancers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False, comment='分析记录 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户 ID'),
    sa.Column('video_id', sa.Integer(), nullable=False, comment='关联视频 ID'),
    sa.Column('analysis_type', sa.String(length=50), nullable=False, comment='分析类型：pose_detection, movement_tracking, score_evaluation'),
    sa.Column('result_data', sa.JSON(), nullable=True, comment='AI 分析的详细结果数据（包含 token_usage）'),
    sa.Column('confidence_score', sa.Float(), nullable=True, comment='置信度分数'),
    sa.Column('processed_at', sa.DateTime(), nullable=False, comment='处理时间 (CST/UTC+8)'),
    sa.Column('model_version', sa.String(length=50), nullable=True, comment='使用的 AI 模型版本'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyses')
    op.drop_table('videos')
    op.drop_table('progress_records')
    op.drop_table('dancers')
    op.drop_table('users')
    # ### end Alembic commands ###
